Repository vesoft-inc/nebula-operator, pull requests merged in 2021-07, with the labels that each got.

#38 ngctl: Nebula Graph Kubernetes Control
  Makefile
  cmd/ngctl/main.go
  go.mod
  go.sum
  pkg/ngctl/cmd/cmd.go
  pkg/ngctl/cmd/console/console.go
  pkg/ngctl/cmd/info/clusterinfo.go
  pkg/ngctl/cmd/info/info.go
  pkg/ngctl/cmd/list/alias.go
  pkg/ngctl/cmd/list/list.go
  pkg/ngctl/cmd/options/options.go
  pkg/ngctl/cmd/use/use.go
  pkg/ngctl/cmd/util/alias.go
  pkg/ngctl/cmd/util/factory.go
  pkg/ngctl/cmd/util/ignore/io.go
  pkg/ngctl/cmd/version/version.go
  pkg/ngctl/config/config.go
  pkg/ngctl/executor/executor.go
  pkg/util/config/config.go
  pkg/util/config/log.go
Labels: feature, ready-for-testing

#39 ngctl: add check command and doc
  doc/user/ngctl_guide.md
  pkg/ngctl/cmd/check/check.go
  pkg/ngctl/cmd/check/check_test.go
  pkg/ngctl/cmd/cmd.go
  pkg/ngctl/cmd/console/console.go
  pkg/ngctl/cmd/console/console_test.go
  pkg/ngctl/cmd/info/info.go
  pkg/ngctl/cmd/list/list.go
  pkg/ngctl/cmd/use/use.go
  pkg/ngctl/cmd/util/factory.go
  pkg/ngctl/cmd/util/factory_test.go
  pkg/ngctl/cmd/version/version.go
  pkg/ngctl/config/config_test.go
Labels: feature, ready-for-testing

#45 e2e vid_type
  tests/e2e/nebulacluster/nebulacluster.go
  tests/e2e/nebulacluster/util.go
Labels: ready-for-testing

#44 fix storageClassName "null" value
  charts/index.yaml
  charts/nebula-cluster-0.1.0.tgz
  charts/nebula-cluster/templates/nebula-cluster.yaml
  charts/nebula-cluster/values.yaml
Labels: bug
