Repository vesoft-inc/nebula-operator, pull requests merged in 2021-06, with the labels that each got.

#19 upgrade golangci-lint to v1.40.1 and fix some lint error
  .golangci.yml
  Makefile
  apis/apps/v1alpha1/template.go
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  pkg/controller/component/graphd_cluster.go
  pkg/controller/component/storaged_scaler.go
  pkg/controller/nebulacluster/nebula_cluster_condition_updater_test.go
  pkg/controller/nebulacluster/nebula_cluster_control_test.go
  pkg/kube/cm.go
  pkg/kube/nebulacluster.go
  pkg/kube/pod.go
  pkg/kube/pv.go
  pkg/kube/pvc.go
  pkg/kube/service.go
  pkg/kube/workload.go
  pkg/nebula/meta_client.go
  pkg/util/controller/unstructured.go
  pkg/webhook/nebulacluster/validating/nebulagraph_create_update_handler.go
  pkg/webhook/statefulset/mutating/statefulset_create_update_handler.go
Labels: ready-for-testing

#22 zap log
  .golangci.yml
  cmd/controller-manager/main.go
  cmd/scheduler/main.go
  go.mod
  pkg/controller/component/graphd_cluster.go
  pkg/controller/component/helper.go
  pkg/controller/component/log.go
  pkg/controller/component/metad_cluster.go
  pkg/controller/component/pvc_gc.go
  pkg/controller/component/reclaimer/log.go
  pkg/controller/component/reclaimer/meta_reconciler.go
  pkg/controller/component/reclaimer/pvc_reclaimer.go
  pkg/controller/component/storaged_cluster.go
  pkg/controller/component/storaged_scaler.go
  pkg/controller/nebulacluster/log.go
  pkg/controller/nebulacluster/nebula_cluster_control.go
  pkg/controller/nebulacluster/nebula_cluster_controller.go
  pkg/kube/cm.go
  pkg/kube/log.go
  pkg/kube/nebulacluster.go
  pkg/kube/pod.go
  pkg/kube/pv.go
  pkg/kube/pvc.go
  pkg/kube/service.go
  pkg/kube/workload.go
  pkg/logging/logging.go
  pkg/nebula/log.go
  pkg/nebula/meta_client.go
  pkg/nebula/storage_client.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/log.go
  pkg/scheduler/extender/predicates/log.go
  pkg/scheduler/extender/predicates/topology.go
  pkg/util/controller/controller.go
  pkg/util/controller/log.go
  pkg/util/controller/unstructured.go
  pkg/webhook/log.go
  pkg/webhook/nebulacluster/validating/log.go
  pkg/webhook/nebulacluster/validating/nebulagraph_create_update_handler.go
  pkg/webhook/nebulacluster/validating/nebulagraph_validation.go
  pkg/webhook/server.go
  pkg/webhook/statefulset/mutating/log.go
  pkg/webhook/statefulset/mutating/statefulset_create_update_handler.go
  pkg/webhook/statefulset/validating/log.go
  pkg/webhook/statefulset/validating/statefulset_create_update_handler.go
  pkg/webhook/statefulset/validating/statefulset_validation.go
  tests/e2e/nebulacluster/nebulacluster.go
  tests/e2e/nebulacluster/util.go
  tests/e2e/suites.go
Labels: enhancement, ready-for-testing

#18 custom parameters
  doc/user/custom_config.md
  pkg/util/config/config.go
  pkg/util/config/config_test.go
Labels: doc affected, enhancement

#29 support envs
  apis/apps/v1alpha1/nebulacluster_common.go
  apis/apps/v1alpha1/nebulacluster_componentter.go
  apis/apps/v1alpha1/nebulacluster_graphd.go
  apis/apps/v1alpha1/nebulacluster_metad.go
  apis/apps/v1alpha1/nebulacluster_storaged.go
  charts/nebula-cluster/templates/nebula-cluster.yaml
  charts/nebula-cluster/values.yaml
  charts/nebula-operator/templates/_helpers.tpl
  charts/nebula-operator/templates/admission-webhook-certificate.yaml
  charts/nebula-operator/templates/admission-webhook-service.yaml
  charts/nebula-operator/templates/controller-manager-deployment.yaml
  charts/nebula-operator/templates/controller-manager-rbac.yaml
  charts/nebula-operator/templates/scheduler-deployment.yaml
  charts/nebula-operator/templates/scheduler-rbac.yaml
  charts/nebula-operator/values.yaml
  doc/user/client_service.md
  doc/user/nebula_cluster_helm_guide.md
  go.mod
  pkg/util/config/config.go
  pkg/util/config/config_test.go
Labels: feature, ready-for-testing

#31 support imagePullSecrets for nebula cluster
  Makefile
  apis/apps/v1alpha1/nebulacluster_common.go
  charts/index.yaml
  charts/nebula-cluster-0.1.0.tgz
  charts/nebula-cluster/templates/nebula-cluster.yaml
  charts/nebula-operator-0.1.0.tgz
Labels: feature, ready-for-testing

#34 feature: support to use the default StorageClass
  apis/apps/v1alpha1/nebulacluster_common.go
  apis/apps/v1alpha1/nebulacluster_componentter.go
  apis/apps/v1alpha1/nebulacluster_graphd.go
  apis/apps/v1alpha1/nebulacluster_metad.go
  apis/apps/v1alpha1/nebulacluster_storaged.go
  charts/nebula-cluster/values.yaml
  doc/user/nebula_cluster_helm_guide.md
Labels: feature, ready-for-testing
